trigger:
- main  # Replace 'main' with your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the appropriate Python version
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pytest pytest-benchmark
    pytest --benchmark-only --benchmark-json=benchmark_results.json
  displayName: 'Run Performance Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'benchmark_results.json'
    artifactName: 'performance-reports'
  displayName: 'Upload Performance Report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'benchmark_results.json'
    artifact: 'performance-report'
  displayName: 'Save Performance Report'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Performance results:"
      cat benchmark_results.json
  displayName: 'Show Performance Results'
