name: Python Performance Tests

# Triggers
on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Use the appropriate Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-benchmark

    # Step 4: Run performance tests
    - name: Run Performance Tests
      run: |
        pytest --benchmark-only --benchmark-json=benchmark_results.json

    # Step 5: Upload performance report as an artifact
    - name: Upload Performance Report
      uses: actions/upload-artifact@v3
      with:
        name: performance-reports
        path: benchmark_results.json

    # Step 6: Display performance results in logs
    - name: Display Performance Results
      run: |
        echo "Performance results:"
        cat benchmark_results.json
